/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--color-bg-page)",
        foreground: "var(--color-text-secondary)",
        surface: "var(--color-bg-surface)",
        elevated: "var(--color-bg-surface-hover)",
        subtle: "var(--color-border-subtle)",
        bright: "var(--color-text-primary)",
        muted: "var(--color-text-muted)",
        faint: "var(--color-text-faint)",
        inverse: "var(--color-text-inverse)",
        accent: "var(--color-accent-primary)",
        "accent-hover": "var(--color-accent-primary-hover)",
        "accent-light": "var(--color-accent-primary-hover)",
        "accent-secondary": "var(--color-accent-secondary)",
        border: "var(--color-border-subtle)",
        glass: "var(--color-bg-glass)",
        "glass-hover": "var(--color-bg-glass-hover)",
        "glass-strong": "var(--color-bg-glass-strong)",
        "glass-border": "var(--color-border-glass)",
        "glass-border-strong": "var(--color-border-glass-strong)",
        overlay: "var(--color-bg-overlay)",
        scrim: "var(--color-bg-scrim)",
        "heading-from": "var(--color-gradient-heading-from)",
        "heading-to": "var(--color-gradient-heading-to)",
        "hero-heading-from": "var(--color-gradient-hero-from)",
        "hero-heading-to": "var(--color-gradient-hero-to)",
        error: "var(--color-status-error)",
        "error-bg": "var(--color-status-error-bg)",
        "error-border": "var(--color-status-error-border)",
        "error-text": "var(--color-status-error-text)",
        success: "var(--color-status-success)",
      },
    },
  },
};
