import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const envClient = createEnv({
  emptyStringAsUndefined: true,
  client: {
    NEXT_PUBLIC_DEV_MODE: z.string(),

    NEXT_PUBLIC_EMAILJS_SERVICE_ID: z.string().optional(),
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: z.string().optional(),
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: z.string().optional(),
    NEXT_PUBLIC_AZURE_REMINDER_API_URL: z.string().optional(),
    NEXT_PUBLIC_LOCAL_REMINDER_API_URL: z.string().optional(),
    // Chatbot
    NEXT_PUBLIC_GEMINI_MODEL_DEFAULT: z.string(),
    NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL: z.string(),
    NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL_APPROVER: z.string(),
    NEXT_PUBLIC_GEMINI_MODEL_RESUME: z.string().optional(),
    NEXT_PUBLIC_GEMINI_MODEL_RESUME_REVIEWER: z.string().optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_DEV_MODE: process.env.NEXT_PUBLIC_DEV_MODE,

    NEXT_PUBLIC_EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID,
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID,
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
    NEXT_PUBLIC_LOCAL_REMINDER_API_URL: process.env.NEXT_PUBLIC_LOCAL_REMINDER_API_URL,
    NEXT_PUBLIC_AZURE_REMINDER_API_URL: process.env.NEXT_PUBLIC_AZURE_REMINDER_API_URL,
    //Chatbot
    NEXT_PUBLIC_GEMINI_MODEL_DEFAULT: process.env.NEXT_PUBLIC_GEMINI_MODEL_DEFAULT,
    NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL: process.env.NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL,
    NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL_APPROVER: process.env.NEXT_PUBLIC_GEMINI_MODEL_FUNC_CALL_APPROVER,
    NEXT_PUBLIC_GEMINI_MODEL_RESUME: process.env.NEXT_PUBLIC_GEMINI_MODEL_RESUME,
    NEXT_PUBLIC_GEMINI_MODEL_RESUME_REVIEWER: process.env.NEXT_PUBLIC_GEMINI_MODEL_RESUME_REVIEWER,
  },
});
